name: 'dhis2: verify app build'

on:
  push:
    branches:
     - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  GIT_AUTHOR_NAME: '@dhis2-bot'
  GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
  GIT_COMMITTER_NAME: '@dhis2-bot'
  GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
  GH_TOKEN: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
  CI: true

jobs:
  install:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Install D2 Scripts
        run: yarn add d2-app-scripts

  
  build:
    runs-on: ubuntu-latest
    needs: []
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: |
            **/build
            !**/node_modules
          retention-days: 1

